Init command for basic_flow example
epiphany-platform/m-azure-kubernetes-service pull request #11
Opened 2020-10-03 20:11 UTC by toszo

Previously "make init" was missing for this example

2020-10-03 20:57 UTC, sk4zuzu requested changes

2020-10-03 20:57 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +init: init-azbi init-azks
This seems to be incorrect. I think (in principle) `init-azks` needs to be executed after `apply-azbi` is done and successful. :thinking:

2020-10-03 20:57 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +makefile_dir_path := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
This is the "optimized" way (uses built-in functions). :+1:
```suggestion
makefile_dir_path := $(patsubst %/,%,$(dir $(realpath $(firstword $(MAKEFILE_LIST)))))
```

2020-10-13 12:20 UTC, mkyc requested changes

2020-10-13 12:20 UTC, mkyc commented on examples/basic_flow/Makefile
> +init: init-azbi init-azks
That is definitely incorrect @toszo. Please have a look [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/modules.md#user-point-of-view) where it's described that you need to perform `init`, `plan` and `apply` cycles for each module.

2020-10-13 12:20 UTC, mkyc commented on examples/basic_flow/Makefile
> +M_SHARED_EXTERNAL ?= $(makefile_dir_path)/$(M_NAME)/shared
@sk4zuzu approach with `/tmp/azks/shared` was aimed (AFAIU) to have some storage place for runtime. I think changing it to something else than `/tmp/` might make some sense but I would not make it `$(makefile_dir_path)/$(M_NAME)/shared` but rather `$(makefile_dir_path)/shared`. It's not shared directory of this module, but for all the elements installed by this example. Also I would add this directory to `.gitignore`.

2020-10-28 09:36 UTC, closed without merging