introduce tests into module
epiphany-platform/m-azure-kubernetes-service pull request #2
Opened 2020-09-22 14:15 UTC by mkyc

2020-10-12 10:41 UTC, atsikham requested changes
Could you add similar changes as was done for `azbi` module to run pipelines? 

https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/22/files#diff-cb7c0d86e98156fc8cab43cb970e18aaR247-R259

We also could do that in another PR.

2020-10-12 10:41 UTC, atsikham commented on .gitignore
> +/tests/repot.xml
May be report.xml ?

2020-10-13 12:56 UTC, mkyc commented
@atsikham I just introduced required changes as you pointed out 👍

2020-10-14 07:06 UTC, atsikham approved these changes

2020-10-14 07:28 UTC, erzetpe approved these changes

2020-10-14 07:50 UTC, merged