Transfer test pipeline to yaml
epiphany-platform/m-azure-kubernetes-service pull request #22
Opened 2020-10-19 13:32 UTC by atsikham

2020-10-20 09:01 UTC, plirglo requested changes

2020-10-20 09:19 UTC, atsikham commented on pipeline.yml
>    name: 'Azure Epiphany cluster - epiphany-build-agents-v2'
Let's check.

2020-10-20 13:13 UTC, plirglo approved these changes

2020-10-20 13:18 UTC, atsikham commented on pipeline.yml
>    name: 'Azure Epiphany cluster - epiphany-build-agents-v2'
[Here](https://abb-epiphany.visualstudio.com/epiphany/_build/results?buildId=3952&view=logs&j=5264e576-3c6f-51f6-f055-fab409685f20) is an example of parameter with an ability to redefine.

2020-10-22 13:05 UTC, mkyc requested changes

2020-10-22 13:05 UTC, mkyc commented on pipeline.yml
> +        displayName: 'Build and Tag image'
Can we use [docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops) here?

2020-10-22 13:11 UTC, atsikham commented on pipeline.yml
> +        displayName: 'Build and Tag image'
We can. We spoke with Irek about this, and his suggestion was to do so, not to have dependency on Azure devops. But docker task is used in publishing images as it allows us easy use secret for registry.

2020-10-22 13:34 UTC, atsikham commented on pipeline.yml
> +          goBin: '/root/go/bin'
You're right, there is no reason to do so.

2020-10-22 13:58 UTC, atsikham commented on pipeline.yml
> +            echo "##vso[task.setvariable variable=PATH]$SET_PATH"
Done in a such way.

2020-10-22 14:02 UTC, mkyc commented on pipeline.yml
> +        displayName: 'Build and Tag image'
But we are using Azure DevOps and this is Azure DevOps pipeline definition ....

2020-10-22 14:40 UTC, plirglo approved these changes

2020-10-22 14:51 UTC, atsikham commented on pipeline.yml
> +        displayName: 'Build and Tag image'
Done in suggested way.

2020-10-22 15:15 UTC, plirglo approved these changes

2020-10-22 15:34 UTC, plirglo approved these changes

2020-10-22 20:35 UTC, mkyc approved these changes

2020-10-22 21:02 UTC, merged