Ability to create AKS in existing subnet
epiphany-platform/m-azure-kubernetes-service pull request #27
Opened 2020-10-29 18:13 UTC by rpudlowski93

PR related to task #7 

- Ability to create AKS in existing subnet added
- Small fixes for tests
- Subnet Name used instead of Subnet ID (more readable and easy)

2020-10-30 15:55 UTC, mkyc requested changes
I wouldn't change `examples/basic_flow` and `examples/basic_flow_devcontainer`. Instead I would copy `examples/basic_flow` to new directory `examples/create_in_existing_subnet` and I would do changes there. I would also remove whole AzBI related part in that new `examples/create_in_existing_subnet/Makefile` file as not related.

2020-10-30 15:55 UTC, mkyc commented on README.md
> +AKS and new subnet will be created in resource group and vnet from [AzBI Module](https://github.com/epiphany-platform/m-azure-basic-infrastructure) or You can join AKS to already existing subnet.
```suggestion
AKS and new subnet will be created in resource group and vnet from [AzBI Module](https://github.com/epiphany-platform/m-azure-basic-infrastructure) or you can create AKS in already existing subnet.
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +* Initialize AzKS module in AzBI:
```suggestion
* Initialize AzKS module in AzBI (without parameters it will extract some knowledge from status file):
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +  or You can run AzKS module in already existing subnet:
```suggestion
  or you can run AzKS module with some parameters (ie.: in already existing subnet by setting `M_SUBNET_NAME`): 
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +  This commad will create configuration file of AzKS module in /tmp/shared/azks/azks-config.yml. You can investigate what is stored in that file.
```suggestion
  This commad will create configuration file of AzKS module in /tmp/shared/azks/azks-config.yml. You can investigate what is stored in that file and change it at will. 
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +* Share kubeconfig with `epicli` tool:
```suggestion

* Extract kubeconfig following way:
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/azks:latest kubeconfig M_ARM_CLIENT_ID=appId M_ARM_CLIENT_SECRET=password M_ARM_SUBSCRIPTION_ID=subscriptionId M_ARM_TENANT_ID=tenantId
```suggestion
  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/azks:latest kubeconfig
```
I don't think azure credentials are required for this command but please double check.

2020-10-30 15:55 UTC, mkyc commented on README.md
> +You will run example of AzBI and AzKS module
```suggestion
You can run example of AzBI and AzKS module using files in `examples` directory. 
```

2020-10-30 15:55 UTC, mkyc commented on README.md
> +cd examples/basic_flow
I'd move this to `examples/create_in_existing_subnet

2020-10-30 15:55 UTC, mkyc commented on resources/defaults.mk
> +M_ADDRESS_PREFIX ?= undefined
is that required?

2020-10-30 19:34 UTC, rpudlowski93 commented on resources/defaults.mk
> +M_ADDRESS_PREFIX ?= undefined
Yes, it is, we have to give some default value eg. "undefined" since we don't want to leave empty variables in some cases, it looks bad in my opinion.

2020-10-30 20:55 UTC, rpudlowski93 commented on README.md
> +AKS and new subnet will be created in resource group and vnet from [AzBI Module](https://github.com/epiphany-platform/m-azure-basic-infrastructure) or You can join AKS to already existing subnet.
Thanks Mateusz! Done! :)

2020-10-30 20:55 UTC, rpudlowski93 commented on README.md
> +  or You can run AzKS module in already existing subnet:
Sure, done:)

2020-10-30 20:55 UTC, rpudlowski93 commented on README.md
> +  This commad will create configuration file of AzKS module in /tmp/shared/azks/azks-config.yml. You can investigate what is stored in that file.
Sure, done:)

2020-10-30 20:55 UTC, rpudlowski93 commented on README.md
> +* Share kubeconfig with `epicli` tool:
Sure, done:)

2020-10-30 20:56 UTC, rpudlowski93 commented on README.md
> +  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/azks:latest kubeconfig M_ARM_CLIENT_ID=appId M_ARM_CLIENT_SECRET=password M_ARM_SUBSCRIPTION_ID=subscriptionId M_ARM_TENANT_ID=tenantId
Sure, done:) Double check done, indeed the parameters are not necessary:) Removed:)

2020-10-30 20:56 UTC, rpudlowski93 commented on README.md
> +You will run example of AzBI and AzKS module
Sure, done:)

2020-10-30 20:56 UTC, rpudlowski93 commented on README.md
> +cd examples/basic_flow
Sure, done:)

2020-10-30 20:56 UTC, rpudlowski93 commented on README.md
> +* Initialize AzKS module in AzBI:
Sure, done:)

2020-11-02 09:09 UTC, mkyc requested changes
I believe those are last documentation comments. All other things look good now.

2020-11-02 09:09 UTC, mkyc commented on examples/create_in_existing_subnet/Makefile
> +M_NAME            ?= mop-module-tests
```suggestion
M_NAME            ?= azks-example-tests
```

2020-11-02 09:09 UTC, mkyc commented on README.md
> +AKS and new subnet will be created in resource group and vnet from [AzBI Module](https://github.com/epiphany-platform/m-azure-basic-infrastructure) or you can create AKS in already existing subnet.
```suggestion
AzKS and new subnet will be created in resource group and vnet from [AzBI Module](https://github.com/epiphany-platform/m-azure-basic-infrastructure) or you can create AzKS in already existing subnet.
```

2020-11-02 09:09 UTC, mkyc commented on README.md
> +  This commad will create configuration file of AzKS module in /tmp/shared/azks/azks-config.yml. You can investigate what is stored in that file and change it at will.
```suggestion
  Previous commad created configuration file of AzKS module in `/tmp/shared/azks/azks-config.yml`. You can investigate what is stored in that file and change it at will.
```

2020-11-02 09:09 UTC, mkyc commented on README.md
> +  Running those commands should create AKS service. You should verify in Azure Portal.
```suggestion
  Running those commands should create AzKS service. You should verify in Azure Portal.
```

2020-11-02 09:09 UTC, mkyc commented on README.md
> +If You want to destroy the AKS, execute above instruction in the same way using `destroy` command instead of `all`.
```suggestion
If You want to destroy the AzKS, execute above instruction in the same way using `destroy` command instead of `all`.
```

2020-11-02 09:36 UTC, atsikham requested changes

2020-11-02 09:36 UTC, atsikham commented on resources/defaults.mk
> +M_SUBNET_NAME ?= undefined
In all other places before we used `unset`. It doesn't matter for me which one we choose, but let's follow one standard.
https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/50d23ec2e422d9ead0e0a6cf311ecac12456f9f5/resources/defaults.mk#L16

2020-11-02 10:24 UTC, rpudlowski93 commented on resources/defaults.mk
> +M_SUBNET_NAME ?= undefined
I understand Your point of view but let's take into account that there is a difference between these two values. Undefined it means that we just undefined these values but they canl be set during terraform scripts automatically or are already set in existing subnet. We don't define them. Unset it means that these values are unset and are not obligatory for usage. Generally these two values are very close each other but I would like to show somehow a small difference.

WDYT?

2020-11-02 13:21 UTC, atsikham commented on resources/defaults.mk
> +M_SUBNET_NAME ?= undefined
Let's use one of them, and if we don't want to change the same in other modules, I would suggest to use `unset`.

2020-11-02 15:08 UTC, rpudlowski93 commented on examples/create_in_existing_subnet/Makefile
> +AZKS := epiphanyplatform/azks:0.0.1
Sure! Done:)

2020-11-02 15:29 UTC, atsikham commented on tests/mocks/config-with-variables/config.yml
> +  disk_size: 36
What is the reason of this change?

2020-11-02 15:37 UTC, rpudlowski93 commented on tests/mocks/config-with-variables/config.yml
> +  disk_size: 36
In defaults variables we have 36 GB and tests fail. I had to change it in order to pass the tests

2020-11-02 15:51 UTC, atsikham commented on tests/mocks/config-with-variables/config.yml
> +  disk_size: 36
@mkyc could you explain the reason of using such value, or it's a mistake? There is also different CIDR ranges such as `10.0.0.0/16` and `10.0.0.1/16`

2020-11-02 16:28 UTC, mkyc commented on tests/mocks/config-with-variables/config.yml
> +  disk_size: 36
Hmmmm ... that is good question :D I have no idea why are tests passing if there are such differences. I believe you could create separate task for this to ensure tests quality.

2020-11-02 16:30 UTC, mkyc approved these changes
LGTM

2020-11-02 17:56 UTC, atsikham approved these changes

2020-11-02 19:48 UTC, merged