Extended parameters list with ability to use complex objects
epiphany-platform/m-azure-kubernetes-service pull request #28
Opened 2020-10-30 14:52 UTC by atsikham

`os_type` is unsupported for `default_node_pool`. If we need to change something and add custom node pools, let's discuss.

2020-11-02 09:25 UTC, mkyc requested changes

2020-11-02 09:25 UTC, mkyc commented on resources/defaults.mk
> +}
Can you use "define/endef" for those two values?

2020-11-02 09:25 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
Do we need to expose those two values?

2020-11-02 09:25 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
I would generally expose as little values as possible and then expose next only on defined need

2020-11-02 09:25 UTC, mkyc commented on resources/defaults.mk
> +M_AUTO_SCALER_PROFILE ?= unset
why is it defined second time in file?

2020-11-02 09:42 UTC, atsikham commented on resources/defaults.mk
> +}
@mkyc I will check if it breaks something (imo it could do so because of indents when processed in yaml), but as you see it's one line.

2020-11-02 09:44 UTC, atsikham commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
It's requested in #8 description. @pprach please help with an answer.

2020-11-02 09:45 UTC, atsikham commented on resources/defaults.mk
> +M_AUTO_SCALER_PROFILE ?= unset
this is a mistake and have to be changed

2020-11-02 09:53 UTC, sk4zuzu requested changes

2020-11-02 09:53 UTC, sk4zuzu commented on workdir/Makefile
> +	@echo "$$M_CONFIG_CONTENT" | python3 -m pyaml > $(M_SHARED)/$(M_MODULE_SHORT)/$(M_CONFIG_NAME)
```suggestion
	@echo "$$M_CONFIG_CONTENT" | yq r --unwrapScalar -p pv -P - '*' > $(M_SHARED)/$(M_MODULE_SHORT)/$(M_CONFIG_NAME)
```

2020-11-02 09:53 UTC, sk4zuzu commented on Dockerfile
> +    apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python &&\
Please check my later comment about `yq r --unwrapScalar -p pv -P - '*'`. I believe python stuff can be dropped. If you have some example that it can't then please share.

2020-11-02 09:53 UTC, sk4zuzu commented on workdir/Makefile
> +	@echo "$$M_CONFIG_CONTENT" | python3 -m pyaml > $(M_SHARED)/$(M_MODULE_SHORT)/$(M_CONFIG_NAME)
I believe this gives the same result without the need for installing whole pip toolchain.

2020-11-02 10:00 UTC, sk4zuzu commented on resources/defaults.mk
> +}
I think `define/endef` implies `=` instead of `?=` :thinking:

2020-11-02 10:01 UTC, sk4zuzu commented on resources/defaults.mk
> +}
Nope it's `?=` just checked :+1::innocent:

2020-11-02 10:21 UTC, sk4zuzu commented on resources/defaults.mk
> +}
I checked it again:
```make
define VAR1
txt1
endef

define VAR2
txt2
endef

VAR3 ?= txt3

VAR4 = txt4

all:
	@echo VAR1 = $(VAR1)
	@echo VAR2 = $(VAR2)
	@echo VAR3 = $(VAR3)
	@echo VAR4 = $(VAR4)
```
```shell
make
VAR1 = txt1
VAR2 = txt2
VAR3 = txt3
VAR4 = txt4
```
```shell
VAR1=hmm1 VAR3=hmm3 VAR4=hmm4 make VAR2=hmm2
VAR1 = txt1
VAR2 = hmm2
VAR3 = hmm3
VAR4 = txt4
```
So in the end define/endef block works like `=`, i.e. it does not read evnvironment variables. :(

2020-11-02 10:23 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
@rpudlowski93 changed description so maybe had a reason for that. I'm generally interested if there are other possible plugins, and if not I would not set them here as defaults but rather in constants with `=`.

2020-11-02 10:33 UTC, sk4zuzu commented on resources/defaults.mk
> +}
```make
define _VAR1
txt1
endef
define _VAR2
txt2
endef
VAR1 ?= _VAR1
VAR2 ?= _VAR2
VAR3 ?= txt3
VAR4 = txt4
all:
	@echo VAR1 = $(VAR1)
	@echo VAR2 = $(VAR2)
	@echo VAR3 = $(VAR3)
	@echo VAR4 = $(VAR4)
```
```shell
VAR1=hmm1 VAR3=hmm3 VAR4=hmm4 make VAR2=hmm2
VAR1 = hmm1
VAR2 = hmm2
VAR3 = hmm3
VAR4 = txt4
```
This is simple enough and gives good results! :heart_eyes:

2020-11-02 10:52 UTC, rpudlowski93 commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
It was just a example what we can customize and should be discussed, but regarding to network policy and network plugin we can set also calico as network policy and kubenet as network plugin. 

However I would decide to stay only with Azure as network plugin and network policy because only this plugin/policy is officially supported by Azure.

2020-11-02 11:00 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
Yeah, same as with OS'es, we decided not to change them. @pprach it would be nice if you could add anything to that discussion. Is network plugin something that you change in your setups?

2020-11-02 14:06 UTC, pprach commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
I'm using Calico (probably default one).
But what is the issue to allow use different one ?

2020-11-02 14:07 UTC, pprach commented on resources/terraform/main.tf
> +    enabled = var.enable_rbac
Is this possible to use AAD integration here?
I think we need this block of code https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_active_directory

2020-11-02 14:27 UTC, atsikham commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
> I'm using Calico (probably default one).
> But what is the issue to allow use different one ?

No issues, but please say whether you need these parameters or not.

2020-11-02 14:28 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
I found this: 
```
variable "network_plugin" {
  type    = string
  default = "azure"
}

variable "network_policy" {
  type    = string
  default = "calico"
}
```
can you help me understand why such choices? 

Problem with allowing too much that we cannot support all setups immediately and I would rather have explicit list of tested values.

2020-11-02 14:40 UTC, atsikham commented
/azp run

2020-11-02 14:59 UTC, pprach commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
network plugin because I found it in documentation and it's working at least for now.
Calico - because I would like to apply network policies on k8s cluster.

2020-11-02 15:41 UTC, atsikham commented on resources/terraform/main.tf
> +    enabled = var.enable_rbac
Added

2020-11-02 15:54 UTC, mkyc commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
Ok .... so having `azure` and `calico` respectively as not-configurable parameters values would be ok for you @pprach now? If you know that we need more values lets have explicite values possible to be passed to module similar how it's done [here](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/resources/terraform/modules/ec2/main.tf#L3-L4).

2020-11-02 15:59 UTC, pprach commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
Yes for now it's ok for me.

2020-11-02 16:25 UTC, atsikham commented on resources/defaults.mk
> +M_NETWORK_POLICY ?= azure
Removed these inputs for now.

2020-11-02 16:46 UTC, mkyc requested changes
Looks good enough in my opinion for now. One general thing in my opinion is that we need to add "Parameters" section in Readme file describing each parameter from "defaults.md" file. There is so many new parameters that it needs to be documented.

2020-11-03 13:18 UTC, mkyc approved these changes
I love it :) ❤️

2020-11-03 13:22 UTC, sk4zuzu approved these changes
LGTM

2020-11-03 13:43 UTC, atsikham commented
/azp run

2020-11-03 14:47 UTC, atsikham commented
/azp run

2020-11-03 15:03 UTC, merged