subnet tests and rewrite
epiphany-platform/m-azure-kubernetes-service pull request #38
Opened 2021-01-20 15:30 UTC by mkyc

2021-02-05 14:35 UTC, atsikham requested changes
A few minor changes requested, nothing critical has been found.

2021-02-11 11:52 UTC, erzetpe commented on pipeline.yml
> +        displayName: 'ensure Go 1.15.2'
Right, we should have similar pattern for all displayed data, as this will make things looking more professional and easy to investigate.

2021-02-11 13:15 UTC, mkyc commented on pipeline.yml
> +        displayName: 'ensure Go 1.15.2'
Yeah, this was already addressed in commit 303f26c56d2bc92d1fd42963dc09f7dc6b94fb76

2021-02-11 14:05 UTC, erzetpe requested changes

2021-02-11 14:05 UTC, erzetpe commented on examples/basic_flow_devcontainer/Makefile
> +#		M_ARM_CLIENT_ID=$$ARM_CLIENT_ID \
Maybe instead of this commented out code short comment with link to previous version or informing where to find previous code would be better?

2021-02-12 12:47 UTC, mkyc commented on cmd/destroy.go
> +		if !reflect.DeepEqual(state.AzKS, &st.AzKSState{}) && state.AzKS.Status != st.Applied {
Discussed and if needed we can change it in future.

2021-02-12 12:47 UTC, mkyc commented on cmd/init.go
> +		if !reflect.DeepEqual(state.AzKS, &st.AzKSState{}) && state.AzKS.Status != st.Initialized && state.AzKS.Status != st.Destroyed {
Discussed and if needed we can change it in future.

2021-02-12 12:50 UTC, mkyc commented on cmd/helpers.go
> +func checkAndLoad(stateFilePath string, configFilePath string) (*azks.Config, *st.State, error) {
So in general there is need to ensure that files already exist in stages using this function. For example in init.go I use `loadState` and `loadConfig` directly as they are prepared to provide new structure or config if needed. Clue of this function it to check if they exist first so in my opinion name is good enough right now.

2021-02-12 12:50 UTC, mkyc commented on examples/basic_flow_devcontainer/Makefile
> +#		M_ARM_CLIENT_ID=$$ARM_CLIENT_ID \
You're right, I did uncommented code and added extended TODO comment.

2021-02-12 14:44 UTC, erzetpe approved these changes

2021-02-12 14:46 UTC, atsikham approved these changes

2021-02-12 15:24 UTC, merged